### ISSUE TITLE
youtube video download very slow how to down fast in app

### ISSUE THREAD

**Issue by DineshJat123** [Hexer10/youtube_explode_dart#231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How should this be implemented**
Write here (if you have considered) a way to implement this feature in the current codebase.
**Additional context**

**Comment by Hazaaa** [comment]
Yeah i agree. Download is really slow, like 2MB song was downloading for 2minutes. Would be nice if this is fixed.

**Comment by Hexer10** [comment]
The download speed should improve with `v1.12.4`.

**Comment by Hazaaa** [comment]
Hey, @Hexer10 , i can confirm that it's fixed! 
Thanks!

**Comment by AhmedAbouelkher** [comment]
@Hexer10 

I'm interested in knowing how you fixed this issue because it exists in many other tools and I don't know where can the issue be.

I viewed this issue [fix](https://github.com/Hexer10/youtube_explode_dart/commit/6dced8e91415dd0135edbd4ecc4075ce21d5cd02)

And the [new API](https://github.com/Hexer10/youtube_explode_dart/blob/master/lib/src/reverse_engineering/youtube_http_client.dart) used
