### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by sanihaq** [Hexer10/youtube_explode_dart#37]

**Comment by Hexer10** [comment]
Even tough  no description was provided, I think I can already answer this.
So theoretically speaking the library already supports the web, but it cannot make the http requests (they are blocked from the browser) to the youtube websites since it has not set the [CORS headers](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Headers), a solution to this is to create an api that fetches the data from the youtube website that has the same origin as your browser,  and send the requests to it.

**Comment by Abhishek0116** [comment]
> Even tough no description was provided, I think I can already answer this.
> So theoretically speaking the library already supports the web, but it cannot make the http requests (they are blocked from the browser) to the youtube websites since it has not set the [CORS headers](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Headers), a solution to this is to create an api that fetches the data from the youtube website that has the same origin as your browser, and send the requests to it.

Can you please explain a bit about your alternet solutation as creating an api and featch data from youtube website.

**Comment by cacianokroth** [comment]
I have the same problem with cors....
