### ISSUE TITLE
[BUG] some youtube videos show only one quality of mix

### ISSUE THREAD

**Issue by MeTubeapp** [Hexer10/youtube_explode_dart#49]
**Describe the bug**
Hello sir your packages is awesome... but i am facing a problem related to mix quality

video url ---> https://youtu.be/zzwRbKI2pn4

sir this video shows only 360p quality and not showing 720p i am using mix (audio and video both)..

but i try for another video also they shows both quality ... i am asking you sir why this happens... please help me sir thanks in advance love from INDIA...

sorry for my bad english...

**Comment by Hexer10** [comment]
It happens because using the `muxed` stream it is not possible to get the best video quality, you should instead try using `videoOnly` and get the best quality from there.
Read more here: https://github.com/Hexer10/youtube_explode_dart#downloading-a-video-stream

Please reopen if you have further issues
